golang-1.25-linux/8cbbeb9a25df0cd15038235e0504a02ae6a1badd0b923d46d99a9db1654704a9:
  size: 59660846
  object_id: bf6c819a-3117-47bf-44ab-043c5f48eb6e
  sha: sha256:7716a0d940a0f6ae8e1f3b3f4f36299dc53e31b16840dbd171254312c41ca12e
golang-1.25-linux/288cfe8883218087eeb75040802f471670df0e64e5c4d360b68b0109830b9329:
  size: 59766394
  object_id: fea7a1fd-9254-4aca-7dfe-d9b84dbd5c96
  sha: sha256:9fa5ffeda4170de60f67f3aa0f824e426421ba724c21e133c1e35d6159ca1bec
golang-1.25-windows/976ff3d53aec4af1244ca8b2ab0be7ffd977dafd6dd805771df8508cb4998087:
  size: 67441487
  object_id: fea4d658-066b-42ee-5d29-2e3366ac8f18
  sha: sha256:6dad204d42719795f22067553b2b042c0e710b32c5a00f6c67892865167fdfd0
golang-1.25-windows/d59b40b0d4a5b7f3359d943bcd143637163db0351db4038ba7a1a490a0a6fbec:
  size: 67437540
  object_id: 65ee0368-45e4-442b-5709-aa35ce7e6ffc
  sha: sha256:c18b46f6aa44dbfcd54a9db19dd2fcc5ad684819addcfcf968aa75dad89a89c8
golang-1.25-windows/fdc6f89451567c145ae473d9dee3b4828cb3c741829125604e98d8e37bbfe51f:
  size: 67419304
  object_id: 47d3e44a-0e6e-4334-78ed-e2eb66d2eb56
  sha: sha256:4a974de310e7ee1d523d2fcedb114ba5fa75408c98eb3652023e55ccf3fa7cab
